input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

backbone:
    [
        [1, DWConv, [32, 3, 2,null,ReLU]],
        [1,InvertedResidualv2,[32,1,2]],
        [4,InvertedResidualv3,[3,1.7,16,0,1,2]],
        [3,InvertedResidualv2,[16,3,1]],
        [3,InvertedResidualv3,[5,2.8,64,0,1,2]],
        [1,Conv,[640,1,1]],
        [1,GlobalAvgPool,[]],
        [1,FixedConv,[9,1,1,null,1,null]]
    ]
